[2022-12-22T11:07:13.264+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:06:56.090288+00:00 [queued]>
[2022-12-22T11:07:13.279+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:06:56.090288+00:00 [queued]>
[2022-12-22T11:07:13.280+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T11:07:13.280+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-22T11:07:13.280+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-22T11:07:13.307+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): RunAPIService> on 2022-12-22 11:06:56.090288+00:00
[2022-12-22T11:07:13.316+0000] {standard_task_runner.py:55} INFO - Started process 4024 to run task
[2022-12-22T11:07:13.321+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'RunAPIService', 'manual__2022-12-22T11:06:56.090288+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmphrrfkm5t']
[2022-12-22T11:07:13.324+0000] {standard_task_runner.py:83} INFO - Job 91: Subtask RunAPIService
[2022-12-22T11:07:13.602+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.RunAPIService manual__2022-12-22T11:06:56.090288+00:00 [running]> on host 1a27c7ed0719
[2022-12-22T11:07:13.771+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=RunAPIService
AIRFLOW_CTX_EXECUTION_DATE=2022-12-22T11:06:56.090288+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-22T11:06:56.090288+00:00
[2022-12-22T11:07:13.774+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-22T11:07:13.775+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'uvicorn app.api_service.main:app --reload --port 3000']
[2022-12-22T11:07:13.798+0000] {subprocess.py:86} INFO - Output:
[2022-12-22T11:07:14.081+0000] {subprocess.py:93} INFO - INFO:     Will watch for changes in these directories: ['/tmp/***tmp2347y1un']
[2022-12-22T11:07:14.082+0000] {subprocess.py:93} INFO - INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)
[2022-12-22T11:07:14.082+0000] {subprocess.py:93} INFO - INFO:     Started reloader process [4025] using StatReload
[2022-12-22T11:07:14.419+0000] {subprocess.py:93} INFO - Process SpawnProcess-1:
[2022-12-22T11:07:14.420+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-22T11:07:14.420+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
[2022-12-22T11:07:14.420+0000] {subprocess.py:93} INFO -     self.run()
[2022-12-22T11:07:14.421+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
[2022-12-22T11:07:14.421+0000] {subprocess.py:93} INFO -     self._target(*self._args, **self._kwargs)
[2022-12-22T11:07:14.421+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
[2022-12-22T11:07:14.422+0000] {subprocess.py:93} INFO -     target(sockets=sockets)
[2022-12-22T11:07:14.423+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
[2022-12-22T11:07:14.423+0000] {subprocess.py:93} INFO -     return asyncio.run(self.serve(sockets=sockets))
[2022-12-22T11:07:14.424+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -     return loop.run_until_complete(main)
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -     return future.result()
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -     config.load()
[2022-12-22T11:07:14.425+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/config.py", line 477, in load
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -     self.loaded_app = import_from_string(self.app)
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/importer.py", line 24, in import_from_string
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -     raise exc from None
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -     module = importlib.import_module(module_str)
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[2022-12-22T11:07:14.426+0000] {subprocess.py:93} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[2022-12-22T11:07:14.427+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[2022-12-22T11:07:14.428+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-12-22T11:07:14.428+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[2022-12-22T11:07:14.428+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[2022-12-22T11:07:14.428+0000] {subprocess.py:93} INFO -   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[2022-12-22T11:07:14.428+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'app'
[2022-12-22T13:51:23.625+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-22T13:51:23.632+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4024. PIDs of all processes in the group: [4025, 4028, 4029, 4024]
[2022-12-22T13:51:23.632+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4024
[2022-12-22T13:51:23.633+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-22T13:51:23.633+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2022-12-22T13:51:23.726+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4024, status='terminated', exitcode=0, started='11:07:13') (4024) terminated with exit code 0
[2022-12-22T13:51:23.728+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4028, status='terminated', started='11:07:14') (4028) terminated with exit code None
[2022-12-22T13:51:23.729+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4029, status='terminated', started='11:07:14') (4029) terminated with exit code None
[2022-12-22T13:51:23.732+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4025, status='terminated', started='11:07:13') (4025) terminated with exit code None
