[2022-12-20T15:31:27.014+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.TransformData manual__2022-12-20T15:31:24.301559+00:00 [queued]>
[2022-12-20T15:31:27.033+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.TransformData manual__2022-12-20T15:31:24.301559+00:00 [queued]>
[2022-12-20T15:31:27.033+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T15:31:27.033+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T15:31:27.034+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T15:31:27.055+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): TransformData> on 2022-12-20 15:31:24.301559+00:00
[2022-12-20T15:31:27.064+0000] {standard_task_runner.py:55} INFO - Started process 4768 to run task
[2022-12-20T15:31:27.072+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'TransformData', 'manual__2022-12-20T15:31:24.301559+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmpadun3qq3']
[2022-12-20T15:31:27.074+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask TransformData
[2022-12-20T15:31:27.223+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.TransformData manual__2022-12-20T15:31:24.301559+00:00 [running]> on host 1a27c7ed0719
[2022-12-20T15:31:27.376+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=TransformData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T15:31:24.301559+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-20T15:31:24.301559+00:00
[2022-12-20T15:31:27.403+0000] {logging_mixin.py:137} INFO - None -------------------
[2022-12-20T15:31:27.405+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/co2balance.py", line 30, in transform_data
    fn = Transform(file_path=extracted_data_file, sheet_names=['Sheet1'])
  File "/opt/airflow/dags/app/populate/cook_stove/clean_project_file.py", line 14, in clean_project_file
    data = pd.read_excel(file_path, sheet_name=sheet_names)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1192, in __init__
    content_or_path=path_or_buffer, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1071, in inspect_excel_format
    content_or_path, "rb", storage_options=storage_options, is_text=False
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 614, in get_handle
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 396, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
[2022-12-20T15:31:27.426+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=co2balance, task_id=TransformData, execution_date=20221220T153124, start_date=20221220T153127, end_date=20221220T153127
[2022-12-20T15:31:27.444+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task TransformData (Invalid file path or buffer object type: <class 'NoneType'>; 4768)
[2022-12-20T15:31:27.481+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T15:31:27.528+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
