[2022-12-20T15:07:00.926+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.ExtractData manual__2022-12-20T15:06:58.268184+00:00 [queued]>
[2022-12-20T15:07:00.976+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: co2balance.ExtractData manual__2022-12-20T15:06:58.268184+00:00 [queued]>
[2022-12-20T15:07:00.977+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T15:07:00.977+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T15:07:00.977+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T15:07:01.044+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): ExtractData> on 2022-12-20 15:06:58.268184+00:00
[2022-12-20T15:07:01.070+0000] {standard_task_runner.py:55} INFO - Started process 3154 to run task
[2022-12-20T15:07:01.068+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'co2balance', 'ExtractData', 'manual__2022-12-20T15:06:58.268184+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/co2balance.py', '--cfg-path', '/tmp/tmp8d92pcpp']
[2022-12-20T15:07:01.071+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask ExtractData
[2022-12-20T15:07:01.451+0000] {task_command.py:389} INFO - Running <TaskInstance: co2balance.ExtractData manual__2022-12-20T15:06:58.268184+00:00 [running]> on host 1a27c7ed0719
[2022-12-20T15:07:01.778+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=CO2balance
AIRFLOW_CTX_DAG_ID=co2balance
AIRFLOW_CTX_TASK_ID=ExtractData
AIRFLOW_CTX_EXECUTION_DATE=2022-12-20T15:06:58.268184+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-20T15:06:58.268184+00:00
[2022-12-20T15:07:02.589+0000] {clean_project_file.py:120} INFO - Raw Data read from excel file completed successfully
[2022-12-20T15:07:02.590+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/app/populate/cook_stove/clean_project_file.py", line 123, in extract_project_data
    projects = projects.append(data, ignore_index=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 8969, in append
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 384, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid
[2022-12-20T15:07:02.625+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=co2balance, task_id=ExtractData, execution_date=20221220T150658, start_date=20221220T150700, end_date=20221220T150702
[2022-12-20T15:07:02.655+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task ExtractData (cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid; 3154)
[2022-12-20T15:07:02.699+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T15:07:02.750+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
